readonlyrest:

    ssl:
      enable: true
      keystore_file: "/usr/share/elasticsearch/ssl/self.jks"
      keystore_pass: KEYSTORE_PASSWORD
      key_pass: KEY_PASSWORD

    response_if_req_forbidden: Forbidden by ReadonlyREST ES plugin

    access_control_rules:

    # We trust Kibana's server side process, full access granted via HTTP authentication
    - name: "::KIBANA-SRV::"
      # auth_key is good for testing, but replace it with `auth_key_sha256`!
      auth_key: KIBANA_USER:KIBANA_PASSWORD
      verbosity: error # don't log successful request

    # Using "Basic HTTP Auth" from browsers, can RW Kibana settings, RO on logstash indices from 2017 .
    - name: "::READ_WRITE_USER::"
      auth_key: RW_USER:RW_PASSWORD
      verbosity: error # don't log successful request

    # Same as above, but cannot change dashboards, visualizations or settings in Kibana
    - name: "::READ_ONLY_USER::"
      auth_key: RO_USER:RO_PASSWORD
      kibana_access: ro
      verbosity: error # don't log successful request


