#################################### Index ####################################

#################################### Paths ####################################
path:
  logs: /usr/share/elasticsearch/logs
  data: /usr/share/elasticsearch/data

network.host: 0.0.0.0



